### ISSUE TITLE
English

### ISSUE THREAD

**Issue by zhangzhizz** [TensorFlowKR/dlcampjeju#27]
I hava a bad englishi,Can i join this program?

**Comment by tarvos21** [comment]
Hi, @zhangzhizz, are you Chinese too? One Chinese here, I also submit an application, 😄 . I think if you really want to learn and do anything about machine learning, computer science, or artificial intelligence, English is the very first language you should learn to read, write and speak, because so many resources are in English, while for Chinese there are only translations that may lose some quality. So now you have reached here, I think your English is good enough to attend any Camp, 👍,because you can let others understand you. Believe in yourself!

**Comment by zhangzhizz** [comment]
Hi, @tarvos21 ,i,am chinese too,nice to meet yoiu here .Thank you for your answer,i just worry about my listening ,i want to know if it have simultaneous interpretation in this camp?

**Comment by tarvos21** [comment]
@zhangzhizz, hmmm, though I have no way to know whether the camp provides simultaneous interpretation service, but I guess the answer is probably no, because first the service could cost much, second it will be more smooth for all participants and mentors to communicate ideas in English directly. But I really think your English is acceptable despite some minor spelling errors, because anyone will have them.

**Comment by zhangzhizz** [comment]
@tarvos21 Thank you,i will consider it seriously,you are so sweat,if i decided to join this camp,we can conmunicate deeply with each other in Korea.

**Comment by tarvos21** [comment]
@zhangzhizz Hope so, bro
